model:
  name: cdrmix-reason-200b
  vocab_size: 50272
  d_model: 12288
  n_layers: 96
  schedule:
    variant: top-of-x
    transformer_pct: 0.25
    interleave_every: 4

blocks:
  transformer:
    attn: mhsa
    n_heads: 96
    rope: true
    ffn_hidden: 49152
  rwkv:
    time_mix: true
    channel_mix: true
    channel_mult: 2.0

moe:
  enabled: true
  scope: ffn_only
  experts: 8
  top_k: 2
  expert_ffn_hidden: 32768
  capacity_factor: 1.25
  aux_losses: [load_balance, z_loss]

reasoning:
  controller:
    max_branches: 4
    accept_threshold: 0.0
    rollback_on_reject: true
    step_budget: 160
  hebbian:
    adapters: plastic-lora
    rank: 24
    alpha: 0.15
    clamp: 2.0
    objective: corr_loss_v1
    decay: 0.992
    commit_policy: on_accept
  rl_memagent:
    algorithm: grpo
    policy: memory-ops
    actions: [summarize, retrieve, splice_window, cache_write]
    rewards:
      task_metric_weight: 1.0
      latency_penalty: 0.006
      stability_bonus: 0.12
    ppo_like:
      horizon: 768
      gamma: 0.998
      lam: 0.965
      clip_ratio: 0.2
      kl_target: 0.015
  memory:
    working:
      kv_summary_stride: 8
      rolling_summary_dim: 1024
    episodic:
      index: faiss
      top_k: 8
      max_tokens: 262144
      write_policy: on_accept

readout:
  tie_embeddings: true

training:
  losses: [ce, rl, hebbian, moe_aux]
  dtype: bfloat16
  grad_clip: 0.8
  rmsnorm_eps: 1e-6
  init_std_scale: 0.8

notes:
  - "Plan tensor + pipeline + sequence parallel; shard MoE experts across nodes."
  - "Tune latency_penalty vs. stability_bonus for throughput vs. quality."
