model:
  name: cdrmix-core-200b
  vocab_size: 50272
  d_model: 12288
  n_layers: 96
  schedule:
    variant: top-of-x
    transformer_pct: 0.25
    interleave_every: 4
  blocks:
    transformer:
      attn: mhsa
      n_heads: 96
      rope: true
      ffn_hidden: 49152
    rwkv:
      time_mix: true
      channel_mix: true
      channel_mult: 2.0
  moe:
    enabled: true
    scope: ffn_only
    experts: 8
    top_k: 2
    expert_ffn_hidden: 32768
    capacity_factor: 1.25
    aux_losses: [load_balance, z_loss]
  readout:
    tie_embeddings: true

training:
  losses: [ce, moe_aux]
  dtype: bfloat16
  grad_clip: 0.8
  init_std_scale: 0.8
  rmsnorm_eps: 1e-6

notes:
  - "Target ~200B active params. Expect substantial memory/throughput needs."
  - "Strongly consider tensor + pipeline parallelism; sequence parallel for MoE."
