model:
  name: cdrmix-reason-4b
  vocab_size: 50272
  d_model: 3072
  n_layers: 36
  schedule:
    variant: top-of-x
    transformer_pct: 0.25
    interleave_every: 4

blocks:
  transformer:
    attn: mhsa
    n_heads: 24
    rope: true
    ffn_hidden: 12288
  rwkv:
    time_mix: true
    channel_mix: true
    channel_mult: 2.0

moe:
  enabled: true
  scope: ffn_only
  experts: 8
  top_k: 2
  expert_ffn_hidden: 8192
  capacity_factor: 1.25
  aux_losses: [load_balance, z_loss]

reasoning:
  controller:
    max_branches: 3
    accept_threshold: 0.0
    rollback_on_reject: true
    step_budget: 96
  hebbian:
    adapters: plastic-lora
    rank: 12
    alpha: 0.18
    clamp: 2.0
    objective: corr_loss_v1
    decay: 0.985
    commit_policy: on_accept
  rl_memagent:
    algorithm: grpo
    policy: memory-ops
    actions: [summarize, retrieve, splice_window, cache_write]
    rewards:
      task_metric_weight: 1.0
      latency_penalty: 0.01
      stability_bonus: 0.1
    ppo_like:
      horizon: 384
      gamma: 0.996
      lam: 0.95
      clip_ratio: 0.2
      kl_target: 0.02
  memory:
    working:
      kv_summary_stride: 8
      rolling_summary_dim: 640
    episodic:
      index: faiss
      top_k: 6
      max_tokens: 32768
      write_policy: on_accept

readout:
  tie_embeddings: true

training:
  losses: [ce, rl, hebbian, moe_aux]
  dtype: bfloat16
  grad_clip: 1.0
  rmsnorm_eps: 1e-6
  init_std_scale: 1.0

notes:
  - "Scales Hebbian rank and memory sizes for 4B."
